/*
MIT License

Copyright (c) 2026 Seregon

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

/**
 * @file http_config.h
 * @brief HTTP server configuration
 */

#ifndef HTTP_CONFIG_H
#define HTTP_CONFIG_H

#include <stdint.h>

/* Compile-time feature toggle */
#ifndef ENABLE_ZHTTPD
#define ENABLE_ZHTTPD 1
#endif

#ifndef ENABLE_HTTP_GZIP
#define ENABLE_HTTP_GZIP 0
#endif

#ifndef HTTP_DEBUG_LOG_HEADERS
#define HTTP_DEBUG_LOG_HEADERS 0
#endif

/*---------------------------------------------------------------------------*
 * Web root directory — no longer used.
 *
 * All static files are now embedded directly in the binary via
 * http_resources.c (generated by tools/generate_resources.py).
 * The filesystem path HTTP_WEB_ROOT is kept as a no-op for backward
 * compatibility with any external code that may reference it.
 *---------------------------------------------------------------------------*/

/* Server configuration */
#define HTTP_DEFAULT_PORT 8888
#define HTTP_MAX_CONNECTIONS 100

/* Buffer sizes.
 *
 * The request buffer also holds JSON bodies (bulk ZIP selections carry dozens
 * of paths), so it is larger than the URI limit below. */
#define HTTP_REQUEST_BUFFER_SIZE 16384
#define HTTP_RESPONSE_BUFFER_SIZE 8192
#define HTTP_URI_MAX_LENGTH 2048
#define HTTP_HEADER_MAX_COUNT 32

/* Keep HTTP sendfile chunks aligned with the FTP zero-copy path. */
#define HTTP_SENDFILE_CHUNK_SIZE (2U * 1024U * 1024U)
#ifndef HTTP_SENDFILE_EAGAIN_RETRIES
#define HTTP_SENDFILE_EAGAIN_RETRIES 16U
#endif
#ifndef HTTP_SENDFILE_EAGAIN_SLEEP_US
#define HTTP_SENDFILE_EAGAIN_SLEEP_US 1000U
#endif

/* Thread stack size (bytes) */
#ifndef HTTP_THREAD_STACK_SIZE
#define HTTP_THREAD_STACK_SIZE (512U * 1024U)
#endif

/* CSRF token length in hex characters (32 hex = 16 random bytes) */
#define HTTP_CSRF_TOKEN_LENGTH 32

/* Gates mutating web filesystem operations and CSRF protection. */
#ifndef ENABLE_WEB_UPLOAD
#define ENABLE_WEB_UPLOAD 1
#endif

/* Larger upload reads reduce event-loop wakeups; SO_RCVBUF is only a hint. */
#ifndef HTTP_UPLOAD_CHUNK_SIZE
#define HTTP_UPLOAD_CHUNK_SIZE    (512U * 1024U)   /* 512 KB per active upload */
#endif

#ifndef HTTP_UPLOAD_RCVBUF_SIZE
#define HTTP_UPLOAD_RCVBUF_SIZE   (2U * 1024U * 1024U) /* 2 MB SO_RCVBUF hint */
#endif

/* OrbisOS needs an explicit send buffer to keep GbE downloads saturated. */
#ifndef HTTP_SNDBUF_SIZE
#if defined(PS5) || defined(PLATFORM_PS5) || defined(PS4) || defined(PLATFORM_PS4)
#define HTTP_SNDBUF_SIZE (4U * 1024U * 1024U) /* 4 MB — bypass OrbisOS clamp */
#else
#define HTTP_SNDBUF_SIZE 0U /* 0 = leave kernel auto-tuning active */
#endif
#endif

#endif /* HTTP_CONFIG_H */
